# 作者：北小菜
# 官网：https://www.yuturuishi.com
# 微信：bilibili_bxc
# 哔哩哔哩主页：https://space.bilibili.com/487906612
# gitee地址：https://gitee.com/Vanishi/rebucca
# github地址：https://github.com/beixiaocai/rebucca
"""
Django settings for framework project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import time
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_UA = "rebucca"
PROJECT_BUILT = "rebucca built on 2026/09/02"
PROJECT_VERSION = "1.004"
PROJECT_FLAG = "rebucca" # rebucca
PROJECT_ADMIN_START_TIMESTAMP = int(time.time()) # 软件启动时间戳（秒单位）

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rebucca-insecure-oam*2x=@ynuv5w*&$*yc-1cjsku-b2@$x*t9!swd+n0glv76'

# SECURITY WARNING: don't run with debug turned on in production!
# 本项目固定使用 Debug 模式：由 Django 内置 staticfiles 提供静态资源，不依赖 WhiteNoise
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # 启用 Gzip 压缩，提升响应性能
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "app.middleware.SimpleMiddleware",  # 拦截器
]

ROOT_URLCONF = 'framework.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
                'app.context_processors.lang_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'framework.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'rebucca.sqlite3',
        # SQLite 性能优化：见下方 connection_created 信号中的 PRAGMA 设置
        'OPTIONS': {
            'timeout': 20,  # Python 端连接超时（秒）
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

#LANGUAGE_CODE = 'zh-hans'
#LANGUAGE_CODE = 'en'
#TIME_ZONE = 'UTC'
USE_I18N = True # 启用国际化
# USE_L10N = True # 启用本地化（如日期、数字格式）
USE_TZ = False
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

""" 静态资源（DEBUG=True：staticfiles 从 STATICFILES_DIRS 直接提供） """
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

SESSION_COOKIE_NAME = 'RebuccaSessionID'
SESSION_EXPIRE_AT_BROWSER_CLOSE=False #会话cookie可以在用户浏览器中保持有效期  True：关闭浏览器则Cookie失效。
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# 防止暴力破解
SESSION_COOKIE_AGE=7*24*60*60   # session过期，单位（秒） 7天=7*24*60*60，1小时=1*60*60

# 允许iframe嵌入
X_FRAME_OPTIONS = 'ALLOWALL'  # 允许所有网站通过iframe嵌入
# X_FRAME_OPTIONS = 'SAMEORIGIN'  # 只允许同源网站嵌入

# 允许大JSON请求体（集群平台通过WebSocket传递base64文件，模型文件最大1000M）
DATA_UPLOAD_MAX_MEMORY_SIZE = 1610612736  # 1.5GB